model: 'YOLO'
dataset_name: 'POSCAL'
classes: 20
in_channels: 3
train_list: '../dataset/voc_train/train_list.txt'
val_list: '../dataset/voc_train/val_list.txt'
names: './dataset/names/pascal_voc.txt'
input_size: 448

gpus: 1
workers: 4
epochs: 500
batch_size: 4

save_freq: 1
save_dir: './saved'

# model Define
backbone: 'YOLOv1'
head: 'YOLOv1_Head'

optimizer: 'adam'
optimizer_options:
  lr: 1e-3
#  nesterov: true
#  momentum: 0.9
  weight_decay: 5e-4

loss: 'YOLOv1_loss'

trainer_options:
  check_val_every_n_epoch: 5
  
# YOLO Parameter
grid_size: 7
num_boxes: 2
